name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Dein Quell-Branch, nicht gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.111.3'

      - name: Build
        run: hugo --minify -s my-site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-site/public
          publish_branch: gh-pages
